### PR TITLE
Use print() function in both Python 2 and Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.

### Description of proposed changes    
What is the goal of this pull request? What does this pull request change?

### Related issue(s)  

Fixes #  
Related to #  

### Testing
What steps should be taken to test the changes you've proposed?  
If you added or changed behavior in the codebase, did you update the tests, or do you need help with this?

### CODE REVIEW

**Comment by jstoja** [comment]
Looks good to me 👍

**Comment by lukelima** [comment]
@trvrb should this PR be approved or are we waiting some major migration to python 3?

**Comment by cclauss** [comment]
Python 2 died 137 days ago.

**Comment by trvrb** [comment]
Thanks for the fixes here! 🙏🏻 I've rebased these changes into `master` with 0bd4375414e40478383e3c2f6b1d1f54d3a7f26a.

**Pull request closed without merging**
